import assert from "node:assert/strict";
import { mkdir, writeFile } from "node:fs/promises";
import { dirname, join } from "node:path";
import test from "node:test";
import { git, limen, scratchRepo } from "./scratch.ts";

test("ticket authors survive another collaborator's edits and lane moves", async (context) => {
	const scratch = await scratchRepo();
	context.after(scratch.cleanup);
	const first = "spec/features/active/F001-first/ticket.md";
	const second = "spec/features/active/F002-second/ticket.md";
	for (const path of [first, second]) await mkdir(dirname(join(scratch.root, path)), { recursive: true });
	await writeFile(join(scratch.root, first), "# First ticket\n\nAn outcome for the first collaborator.\n");
	git(scratch.root, "add", first);
	git(scratch.root, "commit", "--author", "Alice Filer <1234+alice@users.noreply.github.com>", "-m", "file first ticket");
	const firstCommit = git(scratch.root, "rev-parse", "HEAD");
	assert.equal(git(scratch.root, "show", "-s", "--format=%ce", "HEAD"), "limen@example.test");
	await writeFile(join(scratch.root, second), "# Second ticket\n\nA different outcome.\n");
	git(scratch.root, "add", second);
	git(scratch.root, "commit", "--author", "Bob Filer <bob@example.test>", "-m", "file second ticket");
	const secondCommit = git(scratch.root, "rev-parse", "HEAD");
	const moved = "spec/features/done/F001-first/ticket.md";
	await mkdir(dirname(join(scratch.root, moved)), { recursive: true });
	git(scratch.root, "mv", first, moved);
	git(scratch.root, "commit", "--author", "Bob Filer <bob@example.test>", "-m", "move first ticket");
	await writeFile(join(scratch.root, moved), "# First ticket\n\nAn outcome for the first collaborator.\n\nReviewed by Bob.\n");
	git(scratch.root, "commit", "-am", "edit first ticket", "--author", "Bob Filer <bob@example.test>");
	const before = git(scratch.root, "status", "--porcelain");
	const alice = limen(scratch, "ticket-author", moved);
	assert.equal(alice.status, 0, alice.stderr);
	assert.match(alice.stdout, /Author: Alice Filer <1234\+alice@users\.noreply\.github\.com>/);
	assert.match(alice.stdout, /GitHub: @alice/);
	assert.ok(alice.stdout.includes(`Creation commit: ${firstCommit}`), alice.stdout);
	assert.doesNotMatch(alice.stdout, /Bob Filer|Limen Test/);
	const bob = limen(scratch, "ticket-author", second);
	assert.equal(bob.status, 0, bob.stderr);
	assert.match(bob.stdout, /Author: Bob Filer <bob@example\.test>/);
	assert.ok(bob.stdout.includes(`Creation commit: ${secondCommit}`), bob.stdout);
	assert.doesNotMatch(bob.stdout, /GitHub:/);
	assert.equal(git(scratch.root, "status", "--porcelain"), before);
});
